version: '3.8'

services:
  simulator:
    build:
      context: ./hub_image/
      dockerfile: Dockerfile
    container_name: hub_simulator
    volumes:
      - ./hub_image:/src
    entrypoint: /bin/sh -c
    command: |
      chmod +x /src/run_mqtt_publisher.sh && /src/run_mqtt_publisher.sh
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"

  backend:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: server_api
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
      - simulator
    environment:
      - PYTHONPATH=/src
