version: '3.8'

services:
  simulator:
    build: ./hub_image/
    container_name: hub_simulator
    volumes:
      - ./app:/src
    command: sh -c './run_mqtt_publisher.sh'
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"

  backend:
    build: ./app/
    container_name: server_api
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
      - simulator
    command: >
      sh -c 'python /src/mqtt_subscriber.py & uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    environment:
      - PYTHONPATH=/src
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
